name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install "poetry==1.8.3"

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install deps
        run: poetry install

      - name: Pre-commit (lint & security)
        run: poetry run pre-commit run --all-files

      - name: Run tests
        run: poetry run pytest

      - name: Export deps for pip-audit
        run: poetry export -f requirements.txt --without-hashes -o requirements.txt

      - name: pip-audit
        run: pip install pip-audit && pip-audit -r requirements.txt --strict

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t lms-app:ci .
