"""add worktime_config

Revision ID: 8f5b5cfda90a
Revises: 51e132378993
Create Date: 2025-08-15 17:50:04.275579
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f5b5cfda90a"
down_revision = "51e132378993"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worktime_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("time_zone", sa.String(length=64), nullable=True),
        sa.Column("week_start", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("full_day_minutes", sa.Integer(), server_default="480", nullable=False),
        sa.Column("min_apply_unit_minutes", sa.Integer(), server_default="240", nullable=False),
        sa.Column(
            "min_carry_forward_unit_minutes", sa.Integer(), server_default="60", nullable=False
        ),
        sa.Column(
            "accrual_rounding", sa.String(length=8), server_default="nearest", nullable=False
        ),
        sa.Column("deduction_rounding", sa.String(length=8), server_default="ceil", nullable=False),
        sa.Column(
            "carry_forward_rounding", sa.String(length=8), server_default="floor", nullable=False
        ),
        sa.Column("carry_forward_cap_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "enforce_sandwich_rule", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accrual_rounding in ('ceil','floor','nearest') and deduction_rounding in ('ceil','floor','nearest') and carry_forward_rounding in ('ceil','floor','nearest')",
            name="ck_worktime_config_rounding_values",
        ),
        sa.CheckConstraint("week_start BETWEEN 1 AND 7", name="ck_worktime_config_week_start"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "scope", "scope_key", name="uq_worktime_config_scope"),
    )
    op.create_index(op.f("ix_worktime_config_org_id"), "worktime_config", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_worktime_config_org_id"), table_name="worktime_config")
    op.drop_table("worktime_config")
    # ### end Alembic commands ###
