"""baseline

Revision ID: 9d37b3959ece
Revises: 
Create Date: 2025-08-14 11:51:27.226381
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9d37b3959ece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
