"""create departments table

Revision ID: edd8363e4a59
Revises: b9f926bf7e91
Create Date: 2025-08-14 14:15:37.778576
"""

# revision identifiers, used by Alembic.
revision = "edd8363e4a59"
down_revision = "b9f926bf7e91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
